### PR TITLE
Disallow expiry dates before today

### PR DESCRIPTION
**Pull request by febee99**
Minor changes:

- prevent users from entering expiry dates before today's date

### CODE REVIEW

**Comment by JermyTan** [comment]
Are you referring to while adding new items?

**Comment by febee99** [comment]
@JermyTan yup!

**Comment by JermyTan** [comment]
Request changes:
Screenshot 2019-10-11 at 12 20 25 PM
1. Change error msg to reflect the reason why the input is rejected. eg sth along the lines of expiry date should not be before today's date
2. If the item has expired, there will be an error when reading the item's data from JSON file. To reproduce the error, add this item into data/xpire.json.
{
    "name" : "test",
    "expiryDate" : "9/9/2019",
    "reminderThreshold" : "0",
    "tags" : [ ]
}

**Comment by febee99** [comment]
Made some changes as requested. @JermyTan 
1. If the date of an item being added is before today's date, the error message is as displayed below. 
image
*If the date of an item being added is in the incorrect format, the error message remains unchanged.
2. If the json file contains any items with invalid dates, the application will start up with an empty Expiry Date Tracker.

**Comment by JermyTan** [comment]
"2. If the json file contains any items with invalid dates, the application will start up with an empty Expiry Date Tracker."
The problem is expired dates shouldn't be considered invalid dates. If the item becomes expired, the application shouldn't start up with an empty tracker. @febee99

**Comment by JermyTan** [comment]
Looks good 👍🏻

**Pull request merged**
